import type { Domain, MediaType } from "../enums";

/** Which app area a dependency powers, for grouping in the admin status page. */
export type ServiceArea = "Écrans" | "Jeux" | "Livres" | "Système";

/** Health of one external dependency, as surfaced by the admin services page. */
export interface ServiceStatusDto {
  /** Stable identifier, e.g. "tmdb". */
  key: string;
  /** Human label, e.g. "TMDB". */
  label: string;
  area: ServiceArea;
  /**
   * Whether the app hard-fails for its area without this service. `false` for
   * optional enrichers (OMDb ratings) and keyless fallbacks (AniList).
   */
  required: boolean;
  /** Its API key/credentials are present in the environment. */
  configured: boolean;
  /**
   * Live probe result: `true`/`false` when probed, `null` when not probed
   * (unconfigured, or nothing cheap to ping).
   */
  reachable: boolean | null;
  /** Short human note (missing key, HTTP status, error reason…). */
  detail?: string;
  /** Round-trip time of the live probe, in ms. Absent when not probed. */
  latencyMs?: number;
  /** Where to obtain the missing key/credentials, shown when `!configured`. */
  keyUrl?: string;
}

export interface ServiceStatusResponseDto {
  services: ServiceStatusDto[];
  /** When the probes ran (ISO 8601). */
  checkedAt: string;
}

/** One editable sample-data field for a gallery template (e.g. a recipient's display name). */
export interface MailTemplateFieldDto {
  key: string;
  label: string;
  default: string;
}

/** One entry in the admin email-template gallery. */
export interface MailTemplateInfoDto {
  key: string;
  label: string;
  fields: MailTemplateFieldDto[];
}

export interface MailTemplateListResponseDto {
  templates: MailTemplateInfoDto[];
  /** Whether SMTP is configured — test-send is disabled otherwise. */
  smtpConfigured: boolean;
}

/** Rendered preview of one template (with sample data, possibly overridden), never sent. */
export interface MailTemplatePreviewDto {
  subject: string;
  html: string;
  text: string;
}

export interface SendTestEmailRequestDto {
  to: string;
  /** Overrides for the template's editable sample fields, by field key. */
  values?: Record<string, string>;
}

/** Which registered account to target when sending an admin test push. */
export interface SendAdminTestPushRequestDto {
  email: string;
  /** Defaults to a canned admin-test message when omitted. */
  title?: string;
  body?: string;
}

/** Outcome of the push send to one of the account's subscribed devices. */
export interface AdminPushSendOutcomeDto {
  userAgent: string | null;
  ok: boolean;
  /** Present when `ok` is false (rejected/expired subscription, send error…). */
  error?: string;
}

export interface AdminPushSendResponseDto {
  /** How many devices the account had subscribed at send time. */
  subscriptionCount: number;
  results: AdminPushSendOutcomeDto[];
}

/** One device an account has subscribed to push on. */
export interface AdminPushDeviceDto {
  id: string;
  userAgent: string | null;
  createdAt: string;
}

/**
 * Locally-generated architecture diagrams (Mermaid source), for the admin
 * schema page. Both are gitignored dev artifacts — `null` when not generated
 * yet (or not shipped in this deployment).
 */
export interface SchemaGraphResponseDto {
  /** Prisma ERD, from `docs/erd.md` (regenerated by `prisma generate`). */
  erd: string | null;
  /** NestJS module graph, from `docs/modules.md` (regenerated by `pnpm --filter @tracklore/api run graph`). */
  modules: string | null;
}

export type JobStatus = "SUCCESS" | "FAILURE";

/** One completed execution of a scheduled/admin-triggered job. */
export interface JobRunDto {
  id: string;
  jobKey: string;
  startedAt: string;
  finishedAt: string;
  status: JobStatus;
  /** Short human outcome, e.g. "3 notification(s) créée(s)". */
  summary: string | null;
  /** Present only when `status` is "FAILURE". */
  error: string | null;
}

/** One background job the admin can inspect/trigger, with its recent runs. */
export interface JobDto {
  key: string;
  label: string;
  /** Cron schedule, human-readable (e.g. "Toutes les heures"). */
  schedule: string;
  /** Most recent runs first. */
  runs: JobRunDto[];
}

export interface JobListResponseDto {
  jobs: JobDto[];
}

/** Bucket granularity for the admin trend charts. */
export type TrendPeriod = "day" | "week" | "month" | "year";

/** One bucket in a trend series. */
export interface TrendPointDto {
  /** ISO date (UTC) of the bucket's start. */
  periodStart: string;
  count: number;
}

/** The four trend series shown on the admin stats page, all sharing one period. */
export interface AdminTrendsSeriesDto {
  /** Cumulative MediaItem+GameItem+BookItem total, bucket by bucket. */
  catalogGrowth: TrendPointDto[];
  /** EpisodeWatch rows created per bucket, across every account. */
  watchActivity: TrendPointDto[];
  /** Accounts created per bucket. */
  newAccounts: TrendPointDto[];
  /** Notifications created per bucket, across every account. */
  notifications: TrendPointDto[];
}

/** Trend series for one chosen period — the re-queryable part of the stats page. */
export interface AdminTrendsDto {
  period: TrendPeriod;
  /** When the series were computed (ISO 8601). */
  generatedAt: string;
  trends: AdminTrendsSeriesDto;
}

export interface AdminAccountsStatsDto {
  total: number;
  /** How many accounts keep each domain enabled. */
  byDomain: { domain: Domain; count: number }[];
  /** Accounts with at least one active push subscription. */
  withPush: number;
}

export interface AdminCacheStatsDto {
  mediaByType: { type: MediaType; count: number }[];
  totalGames: number;
  totalBooks: number;
  totalSeasons: number;
  totalEpisodes: number;
  /** Tracked media past the 24h refresh TTL — a freshness proxy, not a full browser. */
  staleMediaCount: number;
}

export interface AdminActivityStatsDto {
  totalLibraryEntries: number;
  totalGameEntries: number;
  totalBookEntries: number;
  totalEpisodeWatches: number;
  totalNotifications: number;
  totalPushDevices: number;
}

/** Instance-wide dashboard: cross-account aggregates, distinct from the per-user /stats page. */
export interface AdminStatsDto {
  accounts: AdminAccountsStatsDto;
  cache: AdminCacheStatsDto;
  activity: AdminActivityStatsDto;
  /** Current on-disk size of every app table, in bytes (live snapshot, not tracked over time). */
  databaseBytes: number;
  /** When the aggregates were computed (ISO 8601). */
  generatedAt: string;
  /** Trends at the default weekly granularity; re-query other periods via the trends endpoint. */
  trends: AdminTrendsSeriesDto;
}

/** One registered account, as listed in the admin users page. */
export interface AdminUserDto {
  id: string;
  email: string;
  username: string;
  displayName: string;
  emailVerified: boolean;
  entitlements: string[];
  createdAt: string;
}
